### ISSUE TITLE
Any plans to update for Windows Phone 8.1?

### ISSUE THREAD

**Issue by BrianVallelunga** [jeffwilcox/wp-maps#11]
This looks very useful, but doesn't currently work in 8.1. Thanks.

**Comment by jeffwilcox** [comment]
I've been told that the newer maps controls in Windows Phone 8 and 8.1 are "quick", local, cached, etc., and may replace the functionality that this control does. As I'm not actively doing 8.1 dev work right now, I cannot confirm this, however.

Feel free to use this issue to discuss how it might be useful, if it still is, etc.

**Comment by BrianVallelunga** [comment]
I'm just starting with Windows Phone development, so I'm learning as I go. I know the 8.1 maps control can pull from locally saved maps, but I haven't tried it yet.

I've looked through some of the limited documentation and examples that use the control and I can't figure out if it can generate a non-interactive static map yet. That's my biggest need since I want to put the map onto a pivot control.

When I get to the mapping portion of my app, I'll post what I find here.
