### ISSUE TITLE
Support setting multiple points

### ISSUE THREAD

**Issue by timheuer** [jeffwilcox/wp-maps#4]
Thinking about performance, if someone did want to fully utilize static maps even when providing search results, it might be good to expose a Points DP to enable binding.  This would be a collection of Points (lat, long, label) that you could send to the map.  If provided the provider would supply the static map with the point data on it as well.

**Comment by jeffwilcox** [comment]
Agreed, I started on the math to take Earth projections in to play, but
haven't had time to dedicate to this yet.

Sent from my Windows Phone
From: Tim Heuer
Sent: 2/1/2012 7:34 PM
To: Jeff Wilcox
Subject: [wp-maps] Support setting multiple points (#4)
Thinking about performance, if someone did want to fully utilize
static maps even when providing search results, it might be good to
expose a Points DP to enable binding.  This would be a collection of
Points (lat, long, label) that you could send to the map.  If provided
the provider would supply the static map with the point data on it as
well.

---

Reply to this email directly or view it on GitHub:
https://github.com/jeffwilcox/wp-maps/issues/4

**Comment by jeffwilcox** [comment]
As part of that work I would also expose the current users GPS location
optionally.

Sent from my Windows Phone
From: Tim Heuer
Sent: 2/1/2012 7:34 PM
To: Jeff Wilcox
Subject: [wp-maps] Support setting multiple points (#4)
Thinking about performance, if someone did want to fully utilize
static maps even when providing search results, it might be good to
expose a Points DP to enable binding.  This would be a collection of
Points (lat, long, label) that you could send to the map.  If provided
the provider would supply the static map with the point data on it as
well.

---

Reply to this email directly or view it on GitHub:
https://github.com/jeffwilcox/wp-maps/issues/4

**Comment by jeffwilcox** [comment]
Sorry @timheuer, I don't think I'm planning to invest in this repo any longer :)
