### ISSUE TITLE
Map localization

### ISSUE THREAD

**Issue by myViseu** [jeffwilcox/wp-maps#9]
When used the control doesn't have a setting to control the language according to the phone locale.
This small addiction can improve the control usage.

**Comment by jeffwilcox** [comment]
Interesting. Will have to look into how to implement that.

**Comment by myViseu** [comment]
Thx Jeff

My app will include this fantastic control and that will improve it.
I'm using bing maps and i think the answer is here: http://msdn.microsoft.com/en-us/library/ff701709.aspx.
But any map provider as it's own parâmetros. To achive this goal. 

Best regards
